#75 line information to tokens
frederikja163/SudoScript pull request #76
Opened 2023-06-26 13:26 UTC by Emilorzz

2023-06-26 16:41 UTC, IronicJuice approved these changes

2023-06-27 10:52 UTC, frederikja163 requested changes, later dismissed

2023-06-27 10:52 UTC, frederikja163 commented on SudoScript.Core/Parser.cs
> +        Token unionToken = new Token(TokenType.Identifier, "Union", 0, 0, "");
This should also include some row and collumn definition. Maybe try getting it from the cell token or something.

2023-06-27 18:26 UTC, SolarEarth37 approved these changes
Looks absolute fire my guy

2023-06-27 19:41 UTC, frederikja163 approved these changes

2023-06-27 19:41 UTC, merged